CREATE TABLE PRODUCTS (ProductID INTEGER(7) NOT NULL AUTO_INCREMENT, Name CHAR(40), Price NUMERIC(5,2), Category CHAR(20),PhotoReference VARCHAR(1000), Description VARCHAR(1000), PRIMARY KEY (ProductID));

INSERT INTO PRODUCTS VALUES (1000000, "Traditional Weekly Planner", 20.00, "planner", "images/traditional-weekly-planner.jpg", "Your favorite planner is back, with enough space to hold all of the things you plan to do! This medium-sized weekly version let's you plan out your week at a glace and has a monthly overview.");
INSERT INTO PRODUCTS VALUES (1000001, "Traditional Monthly Planner", 20.00, "planner", "images/traditional-monthly-planner.jpg", "Your favorite planner is back, with enough space to hold all of the things you plan to do! This medium-sized monthly version is perfect for those who only need to plan their major obligations.");
INSERT INTO PRODUCTS VALUES (1000002, "Traditional Daily Planner", 20.00, "planner", "images/traditional-daily-planner.jpg", "Your favorite planner is back, with enough space to hold all of the things you plan to do! This medium-sized daily version is great for those who need to plan out each day down to the minute.");
INSERT INTO PRODUCTS VALUES (1000003, "Large Weekly Planner", 25.00, "planner", "images/large-weekly-planner.jpg", "Your favorite planner is back, with enough space to hold all of the things you plan to do! This large weekly version let's you plan out your week at a glace and has a monthly overview, and its large size lets you see everything at once.");
INSERT INTO PRODUCTS VALUES (1000004, "Large Monthly Planner", 25.00, "planner", "images/large-monthly-planner.jpg", "Your favorite planner is back, with enough space to hold all of the things you plan to do! This large monthly version is perfect for those who only need to plan their major obligations, and its large size lets you see everything at once.");
INSERT INTO PRODUCTS VALUES (1000005, "Large Daily Planner", 25.00, "planner", "images/large-daily-planner.jpg", "Your favorite planner is back, with enough space to hold all of the things you plan to do! This large daily version is great for those who need to plan out each day down to the minute, and its large size lets you see everything at once.");
INSERT INTO PRODUCTS VALUES (1000006, "Small Weekly Planner", 15.00, "planner", "images/small-weekly-planner.jpg", "Your favorite planner is back, with enough space to hold all of the things you plan to do! This small weekly version let's you plan out your week at a glace and has a monthly overview, and its small size fits into your purse or pocket easily.");
INSERT INTO PRODUCTS VALUES (1000007, "Small Monthly Planner", 15.00, "planner", "images/small-monthly-planner.jpg", "Your favorite planner is back, with enough space to hold all of the things you plan to do! This small monthly version is perfect for those who only need to plan their major obligations, and its small size fits into your purse or pocket easily.");
INSERT INTO PRODUCTS VALUES (1000008, "Small Daily Planner", 15.00, "planner", "images/small-daily-planner.jpg", "Your favorite planner is back, with enough space to hold all of the things you plan to do! This small daily version is great for those who need to plan out each day down to the minute, and its small size fits into your purse or pocket easily.");
INSERT INTO PRODUCTS VALUES (1000009, "Textbook Cover", 10.00, "organization", "images/textbook-cover.jpg", "Keep your textbooks safe and sound with this premium cover! Water-resistant and tough as nails, it can withstand any abuse your backpack puts it through!");
INSERT INTO PRODUCTS VALUES (1000010, "Pencil Case", 10.00, "writing", "images/pencil-case.jpg", "We all need pencils. Keep yours together in this pouch that is water-resistant and zips up easily.");
INSERT INTO PRODUCTS VALUES (1000011, "1-Subject Notelook", 15.00, "notelook", "images/1-subject-notelook.jpg", "Our famous Notelook! It's the first in its class for such a low price, with Marie’s patented technology to prevent both pencil and pen from running if your pages get wet. The incredible paper feels and works just like normal paper, but will not buckle 
	and wrinkle if it gets wet and the marks on the paper will not smear. In addition, we’ve created a binding that allows the notebook to be folded on itself like a spiral binding, but is more sturdy than plastic and doesn’t bend like metal. In addition, the edges of the paper are coated in a special binding that prevents paper cuts and dog-eared corners. 
	The binding along the sides has been manufactured so that pages will not rip out unless it is along the perforation on the sides. This, we think, is one of the most important tools a student can have, because you cannot study if your notes are falling apart, or, even worse, missing!");
INSERT INTO PRODUCTS VALUES (1000012, "3-Subject Notelook", 20.00, "notelook", "images/3-subject-notelook.jpg", "Our famous Notelook! It's the first in its class for such a low price, with Marie’s patented technology to prevent both pencil and pen from running if your pages get wet. The incredible paper feels and works just like normal paper, but will not buckle 
	and wrinkle if it gets wet and the marks on the paper will not smear. In addition, we’ve created a binding that allows the notebook to be folded on itself like a spiral binding, but is more sturdy than plastic and doesn’t bend like metal. In addition, the edges of the paper are coated in a special binding that prevents paper cuts and dog-eared corners. 
	The binding along the sides has been manufactured so that pages will not rip out unless it is along the perforation on the sides. This, we think, is one of the most important tools a student can have, because you cannot study if your notes are falling apart, or, even worse, missing!");
INSERT INTO PRODUCTS VALUES (1000013, "5-Subject Notelook", 25.00, "notelook", "images/5-subject-notelook.jpg", "Our famous Notelook! It's the first in its class for such a low price, with Marie’s patented technology to prevent both pencil and pen from running if your pages get wet. The incredible paper feels and works just like normal paper, but will not buckle 
	and wrinkle if it gets wet and the marks on the paper will not smear. In addition, we’ve created a binding that allows the notebook to be folded on itself like a spiral binding, but is more sturdy than plastic and doesn’t bend like metal. In addition, the edges of the paper are coated in a special binding that prevents paper cuts and dog-eared corners. 
	The binding along the sides has been manufactured so that pages will not rip out unless it is along the perforation on the sides. This, we think, is one of the most important tools a student can have, because you cannot study if your notes are falling apart, or, even worse, missing!");
INSERT INTO PRODUCTS VALUES (1000014, "Pocket Notelook", 10.00, "notelook", "images/pocket-notelook.jpg", "Our famous Notelook! It's the first in its class for such a low price, with Marie’s patented technology to prevent both pencil and pen from running if your pages get wet. The incredible paper feels and works just like normal paper, but will not buckle 
	and wrinkle if it gets wet and the marks on the paper will not smear. In addition, we’ve created a binding that allows the notebook to be folded on itself like a spiral binding, but is more sturdy than plastic and doesn’t bend like metal. In addition, the edges of the paper are coated in a special binding that prevents paper cuts and dog-eared corners. 
	The binding along the sides has been manufactured so that pages will not rip out unless it is along the perforation on the sides. This, we think, is one of the most important tools a student can have, because you cannot study if your notes are falling apart, or, even worse, missing!");
INSERT INTO PRODUCTS VALUES (1000015, "3-Ring Binder", 5.00, "organization", "images/3-ring-binder.jpg", "Keep your papers together! This three-ring binder won't break or snap on you, and it comes with a set of hole-punch reinforcements to make sure your papers stay in.");
INSERT INTO PRODUCTS VALUES (1000016, "Highlighter Set", 5.00, "writing", "images/highlighter-set.jpg", "An essential tool for any student, our pastel highlighters make reading notes a pleasure and an effective way to study.");
INSERT INTO PRODUCTS VALUES (1000017, "Pencil Set", 5.00, "writing", "images/pencil-set.jpg", "Cheap pencils that don't sharpen? Erasers that only smear? We don't think so! Our pencils are designed for smooth writing with a reduction in pencil lead smearage.");
INSERT INTO PRODUCTS VALUES (1000018, "Eraser Set", 3.00, "writing", "images/eraser-set.jpg", "Isn't there something oddly satisfying about watching an eraser slowly become smaller and smaller? Well, you won't experience that feeling much with our premium erasers, designed to eliminate marks and last for ages.");
INSERT INTO PRODUCTS VALUES (1000019, "Laptop Cover", 10.00, "organization", "images/laptop-cover.jpg", "Keep your baby safe with one of our gorgeous covers. They're so pretty, you'll wonder why you didn't buy one when you got the computer in the first place.");
INSERT INTO PRODUCTS VALUES (1000020, "Desktop Organizer", 15.00, "organization", "images/desktop-organizer.jpg", "Keep your desk organized with this sturdy organizer. It has sections for your pencils, papers, and whatever other necessities you need but have no place to put.");
INSERT INTO PRODUCTS VALUES (1000021, "Traditional Backpack", 25.00, "bag", "images/traditional-backpack.jpg", "A classic. Bring your books to school in style with our favorite backpack in a muted blue.");
INSERT INTO PRODUCTS VALUES (1000022, "Shoulder Bag", 25.00, "bag", "images/shoulder-bag.jpg", "Who said that you need a backpack to bring things to school? This stylish shoulder bag has plenty of room for all your books and enough padding to make sure your shoulder doesn't die.");
INSERT INTO PRODUCTS VALUES (1000023, "Tote Bag", 25.00, "bag", "images/tote-bag.jpg", "For that fashionista in all of us. Carry your books to class with this beautiful tote, and watch the room turn green with envy.");
INSERT INTO PRODUCTS VALUES (1000024, "Page Flags", 3.00, "organization", "images/page-flags.jpg", "Rather than dog-earing that book again, how about you use one of our handy-dandy page flags to mark your spot? They're also great for annotating your books for class.");
INSERT INTO PRODUCTS VALUES (1000025, "Folder Set", 5.00, "organization", "images/folder-set.jpg", "Whether your take notes on the computer or in a notebook, you're going to get loose papers in class. Make sure you put them in one of these folders so that you don't lose them!");
INSERT INTO PRODUCTS VALUES (1000026, "Paper Trapper", 5.00, "organization", "images/paper-trapper.jpg", "Like the idea of folders, but lose them all the time? Use our paper trapper so that all of your papers are in one spot, always.");
INSERT INTO PRODUCTS VALUES (1000027, "Locker Mirror", 5.00, "organization", "images/locker-mirror.jpg", "Visable booger? Smeared lipstick? Not with our locker mirror! Hang it up in your locker with either the sticky tape or the magnets, and you'll never have to worry about a fashion faux pas again.");
INSERT INTO PRODUCTS VALUES (1000028, "Locker Storage Container", 5.00, "organization", "images/locker-storage-container.jpg", "Sometimes, you need to write yourself a note, but your pen is at the bottom of the bag. Or maybe you want to make sure you always use hand sanitizer after touching the door to your science class. Either way, use our locker organizer to help those loose ends stay where you need them.");
INSERT INTO PRODUCTS VALUES (1000029, "Pen Set", 5.00, "writing", "images/pen-set.jpg", "Some of us use pencils, and then some use the correct type of writing utensil. Our pen set comes in a rainbow of colors to help make your notes pretty, and their ink dries super fast, so you don't need to ever worry about smudges again.");
INSERT INTO PRODUCTS VALUES (1000030, "Morning Plan Notepad", 5.00, "organization", "images/morning-plan-sheet.jpg", "Morning is often the best time to start a routine. What do you want to get done every day? Drink a glass of water? Run a few times around the block? This worksheet is completely customizable and will help motivate you to get it done.");
INSERT INTO PRODUCTS VALUES (1000031, "Daily Sheets", 5.00, "organization", "images/daily-sheets.jpg", "We are firm believers in planning out your day. Writing down what you're going to do when helps alleviate a lot of procrastination. That's what our morning pads are designed for - to help increase productivity, one day at a time.");
INSERT INTO PRODUCTS VALUES (1000032, "Research Paper Checklist", 5.00, "organization", "images/research-paper-checklist.jpg", "Writing research papers can be daunting. Make sure you don't go down the rabbit hole by using this handy checklist, which covers everything from writing a strong thesis to properly formatting sources.");
INSERT INTO PRODUCTS VALUES (1000033, "Essay Checklist", 5.00, "organization", "images/essay-checklist.jpg", "Essays can be tough. Make sure yours is strong by following this checklist. It will walk you through everything from idea generation to polishing, all while breaking your paper down into simple steps that you can complete.");
INSERT INTO PRODUCTS VALUES (1000034, "Budget Sheets", 5.00, "organization", "images/budget-sheets.jpg", "If you're a college student, you know how hard it is to budget your money. Review where you're putting your dollar with these financial tracking sheets that make budgeting simple, not complicated.");
INSERT INTO PRODUCTS VALUES (1000035, "Goal Sheets", 5.00, "organization", "images/goal-sheets.jpg", "Who do you want to be? If you're having a tough time following your dreams, pick up one of our goal packs and use it to launch yourself forward towards your dreams.");
INSERT INTO PRODUCTS VALUES (1000036, "College Application Worksheets", 5.00, "organization", "images/college-appication-worksheets.jpg", "Having a tough time deciding where to go? We can help you keep track of the colleges you are thinking of going to with these sheets.");
INSERT INTO PRODUCTS VALUES (1000037, "College Degree Worksheets", 5.00, "organization", "images/college-degree-worksheets.jpg", "Make sure you stay on track for your degree using these sheets. That way, you'll be able to decide if you have room in your schedule for that fun Chemistry of Cooking class!");
INSERT INTO PRODUCTS VALUES (1000038, "Task List", 5.00, "organization", "images/task-list.jpg", "Life can be overwhelming sometimes. Instead of writing everything you need to do on sticky notes (and losing them), write down everything you need to do here. Then, you can rearrange and assess your work to your hearts content.");
INSERT INTO PRODUCTS VALUES (1000039, "Pomodoro Timer", 8.00, "organization", "images/pomodoro-timer.jpg", "The Pomodoro timer is famous for its ablility to inspire students to get work done. We've made it even better by shaping it into a dog. Now, who says your furry friend can't help you with your homework, instead of eating it?");
INSERT INTO PRODUCTS VALUES (1000040, "White Board Set", 7.00, "organization", "images/white-board-set.jpg", "Your teacher uses one all the time, but do you? Whiteboards can hold any number of lists, ideas, or plans. And ours cleans easy, so that when you need to plan next week's meals, you don't see the week of ramen you just ate.");
INSERT INTO PRODUCTS VALUES (1000041, "Desk Calendar", 7.00, "organization", "images/desk-calendar.jpg", "Need a way to keep marks from appearing on your desk? Use this giant calendar, which has enough space to see all of your major events, plus some fun quotes. As an added bonus, it stops the marks you would have made on the desk from highlighting that book for class.");
INSERT INTO PRODUCTS VALUES (1000042, "Calendar Pad", 8.00, "organization", "images/calendar-pad.jpg", "Always keep track of the date one day at a time with this calendar pad. Rip off each page and start fresh with a new date and a new quote.");
INSERT INTO PRODUCTS VALUES (1000043, "Wall Calendar", 7.00, "organization", "images/wall-calendar.jpg", "See your month at a glance on the wall with this beautiful wall calendar. We've added inspirational quotes to inspire you to keep going.");
INSERT INTO PRODUCTS VALUES (1000044, "Bulletin Board", 30.00, "organization", "images/bulletin-board.jpg", "Prevent your wall from accumulating a ton of holes with this bulletin board. It's perfect for notes, a calendar, and even that gum wrapper that your crush dropped. (Shh, we won't tell.)");
INSERT INTO PRODUCTS VALUES (1000045, "Sticky Notes", 2.00, "organization", "images/sticky-notes.jpg", "Leave yourself a reminder with our cute animal sticky notes. They'll stick to any surface without leaving residue once you finally remember to call Mom!");

